name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Upgrade pip && Install psycopg2-binary 
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary
      - name: Install dependencies 
        run: |
          pip install -r web/requirements.txt
      - name: Run Docker-Compose
        run: docker-compose up -d

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: | 
            asfcjr/desafio-devops_app:latest
            asfcjr/desafio-devops_app:${{github.run_number}}


    
